[package]
name = "bd_checker"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
lambda_runtime.workspace = true
serde_json.workspace = true
shared.workspace = true
tokio.workspace = true
chrono = "0.4.40"
